// Package apidocs Code generated by swaggo/swag. DO NOT EDIT
package apidocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/qr": {
            "post": {
                "description": "Generates a QR code PNG for the provided text with optional icon and custom size",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "qr"
                ],
                "summary": "Generate QR code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Text or URL to encode",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Center icon image (PNG/JPG/GIF)",
                        "name": "icon",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "QR pixel size (64-2048)",
                        "name": "size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "QR code image",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "QR Code Generator API",
	Description:      "API for generating QR codes with optional icon overlay",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
